version: 2
rules:
  - name: "GitHub Actions Secrets"
    pattern: "([A-Za-z0-9_]{10,100})"
    regex: true
    paths:
      - ".github/workflows/*.yml"
    severity: "high"
    tags: 
      - "github-actions"
      - "secrets"

  - name: "GitHub Personal Access Token (PAT)"
    pattern: "(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36}"
    regex: true
    paths:
      - ".github/workflows/*.yml"
      - "**/*.env"
      - "**/*.json"
    severity: "critical"
    tags: 
      - "github"
      - "token"

  - name: "GitHub App Token"
    pattern: "ghu_[A-Za-z0-9]{36}"
    regex: true
    paths:
      - ".github/workflows/*.yml"
      - "**/*.env"
      - "**/*.json"
    severity: "critical"
    tags: 
      - "github"
      - "token"

  - name: "GitHub OAuth Token"
    pattern: "gho_[A-Za-z0-9]{36}"
    regex: true
    paths:
      - ".github/workflows/*.yml"
      - "**/*.env"
      - "**/*.json"
    severity: "critical"
    tags: 
      - "github"
      - "oauth"

  - name: "GitHub Runner Token"
    pattern: "ghr_[A-Za-z0-9]{36}"
    regex: true
    paths:
      - ".github/workflows/*.yml"
      - "**/*.env"
      - "**/*.json"
    severity: "high"
    tags: 
      - "github"
      - "runner"
